### ISSUE TITLE
seqwish bin

### ISSUE THREAD

**Issue by colindaven** [kevsilva/StrainFLAIR#1]
Hi,

I followed the install instructions exactly, which ran without error, yet seqwish cannot be found.

It has been created and exists under the StrainFLAIR/seqwish/bin directory.

Should it actually be copied somewhere else or added to path ?

```
StrainFLAIR$ ls seqwish/bin
seqwish

```

The conda env Strain is still activated

**Comment by colindaven** [comment]
Ok, solved it - I just needed seqwish in my path: so copied it to the conda bin directory. Works now.

`cp seqwish/bin/seqwish Strain/bin/`

**Comment by pierrepeterlongo** [comment]
Yes we still have to improve the way seqwish is integrated to the pipeline.

Thanks for your comment.
