### ISSUE TITLE
Comparision with Real datasets

### ISSUE THREAD

**Issue by Vidushi-0617** [kevsilva/StrainFLAIR#6]
StrainFLAIR is compared on the real datasets (PRJEB42498) which is available for download. Can you please provide the ground truth information of this data set to which your tool was compared, or provide the source where the ground truth information is available.

**Comment by kevsilva** [comment]
Hello,

Data and ground truth are now available with the associated paper: https://pubmed.ncbi.nlm.nih.gov/36369227/

Regards
